# Generated by Django 3.1.1 on 2020-09-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='thought',
            name='date_and_time_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
