# Generated by Django 3.1.1 on 2020-09-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20200924_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_and_time_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
