# Generated by Django 3.1.1 on 2020-09-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_auto_20200924_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
